<?php

namespace Nines\FeedbackBundle\Repository;

/**
 * EntityFlagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityFlagsRepository extends \Doctrine\ORM\EntityRepository
{
}
