# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    nines_user.sender: 'donotreply@%router.request_context.host%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Nines\UserBundle\:
        resource: '../'
        exclude: '../{DependencyInjection,Entity,Exception,Resources,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Nines\UserBundle\Controller\:
        resource: '../Controller'
        tags: ['controller.service_arguments']

    Nines\UserBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: userMenu, alias: nines_user_nav }

    Nines\UserBundle\Services\UserManager:
        arguments:
            $roles: []
            $afterLogin: ~
            $afterRequest: ~
            $afterReset: ~
            $afterLogout: ~
        calls:
            - [ setSender, ['%nines_user.sender%']]
