<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\DublinCoreBundle\Tests\Repository;

use Nines\DublinCoreBundle\Repository\ElementRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class ElementRepositoryTest extends ServiceTestCase {
    private ?ElementRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(ElementRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(5, $this->repo->indexQuery()->execute());
    }

    public function testTypeaheadQuery() : void {
        $this->assertCount(1, $this->repo->typeaheadQuery('label 1')->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(5, $this->repo->searchQuery('paragraph')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::$container->get(ElementRepository::class);
    }
}
