<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\DublinCoreBundle\Tests\Repository;

use Nines\DublinCoreBundle\Repository\ValueRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class ValueRepositoryTest extends ServiceTestCase {
    private ?ValueRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(ValueRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertGreaterThanOrEqual(5, $this->repo->indexQuery()->execute());
    }

    public function testSearchQuery() : void {
        $this->assertGreaterThanOrEqual(5, $this->repo->searchQuery('data')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::$container->get(ValueRepository::class);
    }
}
