<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\BlogBundle\Tests\Repository;

use Nines\BlogBundle\Repository\PageRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class PageRepositoryTest extends ServiceTestCase {
    private ?PageRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(PageRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(2, $this->repo->indexQuery()->execute());
    }

    public function testIndexQueryIncludePrivate() : void {
        $this->assertCount(5, $this->repo->indexQuery(true)->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(2, $this->repo->searchQuery('paragraph')->execute());
    }

    public function testSearchQueryIncludePrivate() : void {
        $this->assertCount(5, $this->repo->searchQuery('paragraph', true)->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::$container->get(PageRepository::class);
    }
}
