<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\BlogBundle\Tests\Repository;

use Nines\BlogBundle\Repository\PostCategoryRepository;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class PostCategoryRepositoryTest extends ServiceTestCase {
    private ?PostCategoryRepository $repo = null;

    public function testSetUp() : void {
        $this->assertInstanceOf(PostCategoryRepository::class, $this->repo);
    }

    public function testIndexQuery() : void {
        $this->assertCount(5, $this->repo->indexQuery()->execute());
    }

    public function testTypeaheadQuery() : void {
        $this->assertCount(1, $this->repo->typeaheadQuery('label 1')->execute());
    }

    public function testSearchQuery() : void {
        $this->assertCount(1, $this->repo->searchQuery('"label 1"')->execute());
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::$container->get(PostCategoryRepository::class);
    }
}
