<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\SolrBundle\Tests\Command;

use Nines\SolrBundle\Services\SolrManager;
use Nines\SolrBundle\TestUtil\ClientTestTrait;
use Nines\UtilBundle\TestCase\CommandTestCase;

class ClearCommandTest extends CommandTestCase {
    use ClientTestTrait;

    private ?SolrManager $manager = null;

    public function testExecute() : void {
        $this->addResponse([
            'responseHeader' => [
                'status' => '0',
                'QTime' => '2.1',
            ],
        ]);
        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:clear');
        $this->assertSame('', $output);
    }

    public function testExecuteError() : void {
        $this->addResponse([], 500);
        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:clear');
        $this->assertStringStartsWith('Clear failed: Solr HTTP error', $output);
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manager = self::$container->get(SolrManager::class);
    }
}
