<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\SolrBundle\Tests\Command;

use Nines\SolrBundle\Services\SolrManager;
use Nines\SolrBundle\TestUtil\ClientTestTrait;
use Nines\UtilBundle\TestCase\CommandTestCase;

class IndexCommandTest extends CommandTestCase {
    use ClientTestTrait;

    private ?SolrManager $manager = null;

    public function testExecute() : void {
        $this->addResponse([]);

        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:index');
        $this->assertStringContainsString('100%', $output);
    }

    public function testExecuteWithClear() : void {
        $this->addResponse([
            'responseHeader' => [
                'QTime' => '2123.132',
            ],
        ]);
        $this->addResponse([]);

        $client = $this->mockClient();
        $this->manager->setClient($client);

        $output = $this->execute('nines:solr:index', ['--clear' => 'true']);
        $this->assertStringContainsString('100%', $output);
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->manager = self::$container->get(SolrManager::class);
    }
}
