<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\SolrBundle\Tests\Metadata;

use Nines\SolrBundle\Metadata\IdMetadata;
use Nines\UtilBundle\Entity\AbstractEntity;
use PHPUnit\Framework\TestCase;

class IdMetadataTest extends TestCase {
    private ?AbstractEntity $entity = null;

    public function testFetch() : void {
        $meta = new IdMetadata();
        $meta->setName('id');
        $meta->setGetter('getId');
        $this->assertSame(124, $meta->fetch($this->entity));
    }

    public function testFetchArgs() : void {
        $meta = new IdMetadata();
        $meta->setName('id');
        $meta->setGetter('getId(true)');
        $this->assertSame(800, $meta->fetch($this->entity));
    }

    protected function setUp() : void {
        parent::setUp();
        $this->entity = new class() extends AbstractEntity {
            public function __construct() {
                parent::__construct();
                $this->id = 124;
            }

            public function __toString() {
                return 'ok';
            }

            public function getId(?bool $a = null) : ?int {
                if ($a) {
                    return 800;
                }

                return parent::getId(); // TODO: Change the autogenerated stub
            }
        };
    }
}
