<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\SolrBundle\Tests\Client;

use Nines\SolrBundle\Client\LoggerPlugin;
use Nines\UtilBundle\TestCase\ServiceTestCase;

class LoggerPluginTest extends ServiceTestCase {
    private ?LoggerPlugin $plugin = null;

    public function testSetup() : void {
        $this->assertInstanceOf(LoggerPlugin::class, $this->plugin);
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->plugin = self::$container->get(LoggerPlugin::class);
    }
}
