<?php

declare(strict_types=1);

/*
 * (c) 2022 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace Nines\UserBundle\Tests\Command;

use Nines\UserBundle\Repository\UserRepository;
use Nines\UserBundle\Services\UserManager;
use Nines\UtilBundle\TestCase\CommandTestCase;

class DemoteUserCommandTest extends CommandTestCase {
    private ?UserRepository $repo = null;

    private ?UserManager $manager = null;

    public function testExecute() : void {
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->manager->promote($user, 'a');

        $output = $this->execute('nines:user:demote', [
            'email' => 'user@example.com',
            'role' => 'a',
        ]);

        $this->assertSame("Role a removed from Unprivileged user.\n", $output);
        $this->em->clear();
        $user = $this->repo->findOneByEmail('user@example.com');
        $this->assertFalse($user->hasRole('a'));
    }

    protected function setUp() : void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = self::$container->get(UserRepository::class);
        $this->manager = self::$container->get(UserManager::class);
    }
}
