parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nines\SolrBundle\:
    resource: '../'
    exclude: '../{Annotation,DependencyInjection,Entity,Metadata,Resources,Tests}'

  Nines\SolrBundle\DataCollector\RequestCollector:
    tags:
      - { name: data_collector, template: '@NinesSolr/collector/toolbar.html.twig', id: 'solr.request_collector' }

  # Make sure the client factor is picked up as a service so it can be used
  # later.
  Nines\SolrBundle\Client\ClientFactory: ~

  # Solarium clients are constructed by the factory, not directly.
  Solarium\Client:
    factory: [ '@Nines\SolrBundle\Client\ClientFactory', 'build' ]

  Nines\SolrBundle\EventListener\IndexSubscriber:
    tags:
      - { name: 'doctrine.event_subscriber' }

  Nines\SolrBundle\Mapper\EntityMapperFactory:
    arguments: [ '%kernel.environment%']

  Nines\SolrBundle\Mapper\EntityMapper:
    factory: [ '@Nines\SolrBundle\Mapper\EntityMapperFactory', 'build' ]

  Nines\SolrBundle\Services\SolrManager:
    arguments:
      $enabled: '%nines_solr.enabled%'
      $pageSize: '%nines_solr.page_size%'
