parameters:
    nines.maker.fixture_count: 5

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Nines\MakerBundle\:
        resource: '../*'
        exclude: '../{DependencyInjection,Entity,Resources,Tests}'

    Nines\MakerBundle\Maker\:
        resource: '../Maker'
        tags:
            - { name: 'maker.command' }
        calls:
            - [ setDoctrineHelper, [ '@maker.doctrine_helper'] ]
            - [ setFormTypeRenderer, [ '@maker.renderer.form_type_renderer'] ]
            - [ setFixtureCount, ['%nines.maker.fixture_count%'] ]
