nines_feedback:
    default_status: submitted
    public_status: published
    subject: New feedback received
    sender: noreply@example.com
    recipients:
        - user@example.com
        - another@example.com
