<?php

namespace Nines\FeedbackBundle\Repository;

/**
 * FlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlagRepository extends \Doctrine\ORM\EntityRepository
{
}
