<?php

namespace Nines\FeedbackBundle\Repository;

/**
 * FlagEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlagEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
